# fly.toml app configuration file generated for mecanografy-game on 2025-04-09T14:58:08-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mecanografy-game'
primary_region = 'mad'

[build]
  dockerfile = "./Dockerfile"

[env]
  PORT = '8080'
  NODE_ENV = 'production'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
